export const MENU_CATEGORY_REPOSITORY = Symbol('MENU_CATEGORY_REPOSITORY');
export const MENU_ITEM_REPOSITORY = Symbol('MENU_ITEM_REPOSITORY');
export const CATEGORY_PLACEMENT_REPOSITORY = Symbol('CATEGORY_PLACEMENT_REPOSITORY');
